### ISSUE TITLE
Improve the data aggregation approach

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/MouseGastrulationData#10]
https://github.com/MarioniLab/MouseGastrulationData/blob/cf0bd3594c221fcbe26265efb052428aa68adf28/R/getProcOrRaw.R#L22-L44

Can be pretty inefficient. Every `SingleCellExperiment::cbind` requires creation of an increasingly large temporary SCE, which incurs time and memory overhead from combining data. 

It is better to collect all of the individual components together into lists, combine each component as appropriate using `do.call(cbind, ...)`, and then call `SingleCellExperiment()` on the result.

**Comment by jonathangriffiths** [comment]
Could you have a quick peek at PR #11 and see if I've missed any easy wins for the changes I've made?
