### ISSUE TITLE
Package not available for R 4.1.0

### ISSUE THREAD

**Issue by MikhaelManurung** [MarioniLab/MouseGastrulationData#13]
Dear maintainers,

I tried to install the development version (Bioc 3.13) of this package but received the following error:

```
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable) (2021-02-03 r79933)
Installing package(s) 'MouseGastrulationData'
Warning message:
package ‘MouseGastrulationData’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Installing-packages
```

Here's my system info:

```
R Under development (unstable) (2021-02-03 r79933)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)
```

Do you have any suggestion to solve this? Thanks in advance.

Best regards,
Mikhael

**Comment by jonathangriffiths** [comment]
Hi Mikhael,

I suspect this is an issue with our current build on the Bioc build system - there are some changes with SpatialExperiment which have broken my existing code, but there has not been a successful SpatialExperiment build with the completed changes yet! Once that is working, I intend to update MGD to build properly.

Sorry for the inconvenience - I'll try to let you know once it's back up and running.

Jonny

**Comment by jonathangriffiths** [comment]
I've made and pushed the changes. If you want to install the package, you should be able to do so from the github version (e.g. with devtools). You might also need to install the github version of SpatialExperiment.

Let me know if there are any further tissues!

Jonny

**Comment by MikhaelManurung** [comment]
Thanks for the prompt response, Jonny. I can confirm that the installation works now.
