### ISSUE TITLE
Unable to download sample 36

### ISSUE THREAD

**Issue by carissaynchen** [MarioniLab/MouseGastrulationData#17]
Hello, when I attempt to download the data using

`sce <- EmbryoAtlasData(type="processed")`

I get this error:

```
loading from cache
Error: failed to load resource
  name: EH2735
  title: Atlas processed counts (sample 36)
  reason: error reading from connection
```

Is sample 36 available for download?

**Comment by jonathangriffiths** [comment]
Hi there,

I can run fine `sce <- EmbryoAtlasData(type="processed", sample = 36)` in Bioc 3.14.

Can you try running this? I wonder if the server was briefly down.

If it doesn't work, please could you let me know the software versions that you're using and I'll have a think.

Cheers

**Comment by jonathangriffiths** [comment]
Assuming you have resolved this now.

**Comment by carissaynchen** [comment]
Hi, sorry for the delayed response.

I ran the above and I get this error:

`> sce = EmbryoAtlasData(type="processed", sample=36)
snapshotDate(): 2021-10-19
see ?MouseGastrulationData and browseVignettes('MouseGastrulationData') for documentation
loading from cache
Error: failed to load resource
  name: EH2735
  title: Atlas processed counts (sample 36)
  reason: error reading from connection`

This is my session info:

`─ Session info ──────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Big Sur 10.16
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_AU.UTF-8
 ctype    en_AU.UTF-8
 tz       Australia/Sydney
 date     2022-02-04
 rstudio  1.4.1106 Tiger Daylily (desktop)
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────────────
 package                * version  date (UTC) lib source
 AnnotationDbi            1.56.2   2021-11-09 [1] Bioconductor
 AnnotationHub            3.2.1    2022-01-23 [1] Bioconductor
 assertthat               0.2.1    2019-03-21 [1] CRAN (R 4.1.0)
 beachmat                 2.10.0   2021-10-26 [1] Bioconductor
 beeswarm                 0.4.0    2021-06-01 [1] CRAN (R 4.1.0)
 Biobase                * 2.54.0   2021-10-26 [1] Bioconductor
 BiocFileCache            2.2.1    2022-01-23 [1] Bioconductor
 BiocGenerics           * 0.40.0   2021-10-26 [1] Bioconductor
 BiocManager              1.30.16  2021-06-15 [1] CRAN (R 4.1.0)
 BiocNeighbors            1.12.0   2021-10-26 [1] Bioconductor
 BiocParallel             1.28.3   2021-12-09 [1] Bioconductor
 BiocSingular             1.10.0   2021-10-26 [1] Bioconductor
 BiocVersion              3.14.0   2021-05-19 [1] Bioconductor
 Biostrings               2.62.0   2021-10-26 [1] Bioconductor
 bit                      4.0.4    2020-08-04 [1] CRAN (R 4.1.0)
 bit64                    4.0.5    2020-08-30 [1] CRAN (R 4.1.0)
 bitops                   1.0-7    2021-04-24 [1] CRAN (R 4.1.0)
 blob                     1.2.2    2021-07-23 [1] CRAN (R 4.1.0)
 BumpyMatrix              1.2.0    2021-10-26 [1] Bioconductor
 cachem                   1.0.6    2021-08-19 [1] CRAN (R 4.1.0)
 cli                      3.1.0    2021-10-27 [1] CRAN (R 4.1.0)
 colorspace               2.0-2    2021-06-24 [1] CRAN (R 4.1.0)
 crayon                   1.4.2    2021-10-29 [1] CRAN (R 4.1.0)
 curl                     4.3.2    2021-06-23 [1] CRAN (R 4.1.0)
 DBI                      1.1.1    2021-01-15 [1] CRAN (R 4.1.0)
 dbplyr                   2.1.1    2021-04-06 [1] CRAN (R 4.1.0)
 DelayedArray             0.20.0   2021-10-26 [1] Bioconductor
 DelayedMatrixStats       1.16.0   2021-10-26 [1] Bioconductor
 digest                   0.6.29   2021-12-01 [1] CRAN (R 4.1.0)
 dplyr                    1.0.7    2021-06-18 [1] CRAN (R 4.1.0)
 dqrng                    0.3.0    2021-05-01 [1] CRAN (R 4.1.0)
 DropletUtils             1.14.2   2022-01-09 [1] Bioconductor
 edgeR                    3.36.0   2021-10-26 [1] Bioconductor
 ellipsis                 0.3.2    2021-04-29 [1] CRAN (R 4.1.0)
 ExperimentHub            2.2.1    2022-01-23 [1] Bioconductor
 fansi                    0.5.0    2021-05-25 [1] CRAN (R 4.1.0)
 fastmap                  1.1.0    2021-01-25 [1] CRAN (R 4.1.0)
 filelock                 1.0.2    2018-10-05 [1] CRAN (R 4.1.0)
 generics                 0.1.1    2021-10-25 [1] CRAN (R 4.1.0)
 GenomeInfoDb           * 1.30.0   2021-10-26 [1] Bioconductor
 GenomeInfoDbData         1.2.7    2021-12-20 [1] Bioconductor
 GenomicRanges          * 1.46.1   2021-11-18 [1] Bioconductor
 ggbeeswarm               0.6.0    2017-08-07 [1] CRAN (R 4.1.0)
 ggplot2                * 3.3.5    2021-06-25 [1] CRAN (R 4.1.0)
 ggrepel                  0.9.1    2021-01-15 [1] CRAN (R 4.1.0)
 glue                     1.6.0    2021-12-17 [1] CRAN (R 4.1.0)
 gridExtra                2.3      2017-09-09 [1] CRAN (R 4.1.0)
 gtable                   0.3.0    2019-03-25 [1] CRAN (R 4.1.0)
 HDF5Array                1.22.1   2021-11-14 [1] Bioconductor
 htmltools                0.5.2    2021-08-25 [1] CRAN (R 4.1.0)
 httpuv                   1.6.5    2022-01-05 [1] CRAN (R 4.1.2)
 httr                     1.4.2    2020-07-20 [1] CRAN (R 4.1.0)
 interactiveDisplayBase   1.32.0   2021-10-26 [1] Bioconductor
 IRanges                * 2.28.0   2021-10-26 [1] Bioconductor
 irlba                    2.3.5    2021-12-06 [1] CRAN (R 4.1.0)
 KEGGREST                 1.34.0   2021-10-26 [1] Bioconductor
 knitr                    1.37     2021-12-16 [1] CRAN (R 4.1.0)
 later                    1.3.0    2021-08-18 [1] CRAN (R 4.1.0)
 lattice                  0.20-45  2021-09-22 [1] CRAN (R 4.1.2)
 lifecycle                1.0.1    2021-09-24 [1] CRAN (R 4.1.0)
 limma                    3.50.0   2021-10-26 [1] Bioconductor
 locfit                   1.5-9.4  2020-03-25 [1] CRAN (R 4.1.0)
 magick                   2.7.3    2021-08-18 [1] CRAN (R 4.1.0)
 magrittr                 2.0.1    2020-11-17 [1] CRAN (R 4.1.0)
 Matrix                   1.3-4    2021-06-01 [1] CRAN (R 4.1.2)
 MatrixGenerics         * 1.6.0    2021-10-26 [1] Bioconductor
 matrixStats            * 0.61.0   2021-09-17 [1] CRAN (R 4.1.0)
 memoise                  2.0.1    2021-11-26 [1] CRAN (R 4.1.0)
 mime                     0.12     2021-09-28 [1] CRAN (R 4.1.0)
 MouseGastrulationData  * 1.8.0    2021-10-30 [1] Bioconductor
 munsell                  0.5.0    2018-06-12 [1] CRAN (R 4.1.0)
 pillar                   1.6.4    2021-10-18 [1] CRAN (R 4.1.0)
 pkgconfig                2.0.3    2019-09-22 [1] CRAN (R 4.1.0)
 png                      0.1-7    2013-12-03 [1] CRAN (R 4.1.0)
 promises                 1.2.0.1  2021-02-11 [1] CRAN (R 4.1.0)
 purrr                    0.3.4    2020-04-17 [1] CRAN (R 4.1.0)
 R.methodsS3              1.8.1    2020-08-26 [1] CRAN (R 4.1.0)
 R.oo                     1.24.0   2020-08-26 [1] CRAN (R 4.1.0)
 R.utils                  2.11.0   2021-09-26 [1] CRAN (R 4.1.0)
 R6                       2.5.1    2021-08-19 [1] CRAN (R 4.1.0)
 rappdirs                 0.3.3    2021-01-31 [1] CRAN (R 4.1.0)
 Rcpp                     1.0.7    2021-07-07 [1] CRAN (R 4.1.0)
 RCurl                    1.98-1.5 2021-09-17 [1] CRAN (R 4.1.0)
 rhdf5                    2.38.0   2021-10-26 [1] Bioconductor
 rhdf5filters             1.6.0    2021-10-26 [1] Bioconductor
 Rhdf5lib                 1.16.0   2021-10-26 [1] Bioconductor
 rjson                    0.2.21   2022-01-09 [1] CRAN (R 4.1.2)
 rlang                    0.4.12   2021-10-18 [1] CRAN (R 4.1.0)
 RSQLite                  2.2.9    2021-12-06 [1] CRAN (R 4.1.0)
 rstudioapi               0.13     2020-11-12 [1] CRAN (R 4.1.0)
 rsvd                     1.0.5    2021-04-16 [1] CRAN (R 4.1.0)
 S4Vectors              * 0.32.3   2021-11-21 [1] Bioconductor
 ScaledMatrix             1.2.0    2021-10-26 [1] Bioconductor
 scales                   1.1.1    2020-05-11 [1] CRAN (R 4.1.0)
 scater                 * 1.22.0   2021-10-26 [1] Bioconductor
 scuttle                * 1.4.0    2021-10-26 [1] Bioconductor
 sessioninfo              1.2.2    2021-12-06 [1] CRAN (R 4.1.0)
 shiny                    1.7.1    2021-10-02 [1] CRAN (R 4.1.0)
 SingleCellExperiment   * 1.16.0   2021-10-26 [1] Bioconductor
 sparseMatrixStats        1.6.0    2021-10-26 [1] Bioconductor
 SpatialExperiment      * 1.4.0    2021-10-26 [1] Bioconductor
 SummarizedExperiment   * 1.24.0   2021-10-26 [1] Bioconductor
 tibble                   3.1.6    2021-11-07 [1] CRAN (R 4.1.0)
 tidyselect               1.1.1    2021-04-30 [1] CRAN (R 4.1.0)
 utf8                     1.2.2    2021-07-24 [1] CRAN (R 4.1.0)
 vctrs                    0.3.8    2021-04-29 [1] CRAN (R 4.1.0)
 vipor                    0.4.5    2017-03-22 [1] CRAN (R 4.1.0)
 viridis                  0.6.2    2021-10-13 [1] CRAN (R 4.1.0)
 viridisLite              0.4.0    2021-04-13 [1] CRAN (R 4.1.0)
 withr                    2.4.3    2021-11-30 [1] CRAN (R 4.1.0)
 xfun                     0.29     2021-12-14 [1] CRAN (R 4.1.0)
 xtable                   1.8-4    2019-04-21 [1] CRAN (R 4.1.0)
 XVector                  0.34.0   2021-10-26 [1] Bioconductor
 yaml                     2.2.1    2020-02-01 [1] CRAN (R 4.1.0)
 zlibbioc                 1.40.0   2021-10-26 [1] Bioconductor`

**Comment by LTLA** [comment]
Possibly a corrupt file in the cache, rather than any network issue. Try forcing a new download:
```r
library(ExperimentHub)
ehub <- ExperimentHub()
ehub[["EH2735", force=TRUE]]
```

**Comment by carissaynchen** [comment]
Thanks, it works now!
