### ISSUE TITLE
Reference Database

### ISSUE THREAD

**Issue by carlosj-rr** [MarioniLab/MouseGastrulationData#18]
This is not exactly an issue about the programming, but what was the version of the Ensembl reference database used? I can't find a subset of genes anywhere, I've already checked in the fasta CDS datasets of Ensembl from version 84 to version 105.

Thanks a lot.

**Comment by jonathangriffiths** [comment]
Hi,

The scRNA-seq data is based on Ensembl 92. Do you mean that data, the ATAC data, or the seqFISH data?

What do you mean by "find a subset of genes"? There is also the td-Tomato construct added to the chimaera datasets which might throw things off.

Jonny

**Comment by carlosj-rr** [comment]
Hello Jonny,

thanks for your quick answer. Sorry for being unclear. For my current project, I'm using your dataset to extract a set of cells that were identified as neural cells by Tarashansky et al. (2021 - _eLife_), based on their SAMap algorithm.

So, I've taken the whole MouseGastrulationData::EmbryoAtlasData() dataset, and extracted only the cells that were identified by Tarashansky et al. as neural, and from those, all the genes that were expressed in the cells. I also thought that the chimaeras could give some problems, but I was using the results from the publication mentioned above, and unless I was using all 36 samples, I could not retrieve all the neural cells. I ended up with 19,992 putative neural genes, identified by their Ensembl ID.

I needed the full-length transcript of each of those genes, but I couldn't find hits for 264 IDs in the current (105/GRCm39) mouse Ensembl transcriptome, which I had downloaded previously from BioMart. So I made a list of all 264 gene IDs, and submitted them to BioMart, and consistently resulted in empty files. This led me to search them one by one, in ensembl.org, and I noticed that some of them had no hits at all, so I googled some, and found hits on other databases such as BGee and Angiogenes.

So I thought that maybe I was searching the wrong database, and made a webcrawler that downloaded the FASTA CDS databases from Ensembl's FTP sites, and had it fetch all mouse databases from version 84 to 105, and check on each what percent of the 264 IDs were missing. The lowest percentage I had was ~80% missing (Ensembl 84-92), and the highest was 100% missing (Ensembl 103-105). In between Ensembl 93-105, the total missing was about 94%.

The list of the 264 genes is attached: [Remaining_Mm_NC_genes.csv](https://github.com/MarioniLab/MouseGastrulationData/files/8032437/Remaining_Mm_NC_genes.csv).

I'm sorry if it's something I've missed, but I've done my best to explore alternate routes before writing to you.

Best wishes,

Carlos

**Comment by jonathangriffiths** [comment]
That is very thorough!

The chimaeras are accessed by different functions, so you are safe there

I can reproduce some of the issues you have seen with gene IDs being missing (even in Ensembl 92). The only black box I can think of in the processing pipeline is whatever Cellranger does with the annotations provided, and I don't know that well.

If I were in your position, I think I would just drop those genes - I have found that those without stable Ensembl ID tend to be the dodgiest/least reliable transcripts/genes, and in any case they are a very small subset of the total number of genes you're looking at.

Sorry I can't solve this for you - but sticking with Ensembl 92 would be the most "authentic" way to proceed.

Jonny

**Comment by carlosj-rr** [comment]
OK, thanks for the insight! That helps. Thank you for your time.

-Carlos
