### ISSUE TITLE
Request for featureLoadings of Atlas Data

### ISSUE THREAD

**Issue by mtekman** [MarioniLab/MouseGastrulationData#19]
I've been able to extract the UMAP and PCA embeddings from the Embryo Atlas Data....

```
library(Seurat)
library(MouseGastrulationData)
metatab <- AtlasSampleMetadata[AtlasSampleMetadata$stage %in% c("E6.5", "E6.75"),]
sce <- EmbryoAtlasData(samples = metatab$sample)
… code to create Seurat Object …
myseurat[["pca"]] <- CreateDimReducObject(embeddings = reducedDim(sce, "pca.corrected"), key = "pca")
myseurat[["umap"]] <- CreateDimReducObject(embeddings = reducedDim(sce, "umap"), key = "umap")
```

... but I've not been able to access the feature loadings that perform the embedding and would enable me to project my data onto the Gastrulation data

```
featureLoadings(sce)
```

gives an error, and searching through the object with `str(sce)` has not yielded any list of gene loadings I can use.

Ideally I should be able to find a matrix that has data such as

```
##                      PC_1         PC_2         PC_3         PC_4         PC_5
## NOC2L         0.005988064 -0.000904343  0.000242157 -0.007422069 -0.001640398
## RP11-54O7.17 -0.026776336  0.058175265 -0.044659878 -0.099503493 -0.016678441
## HES4         -0.045886747  0.011753673 -0.032254068  0.053464200  0.040064504
## ISG15        -0.056041490 -0.051061844  0.041857912 -0.029064566  0.001042123
## C1orf159     -0.006747477 -0.004160298 -0.003717022  0.002793677 -0.009359661
## TNFRSF18      0.003163395  0.016739857  0.015435265 -0.003986555  0.065950026
```

instead of (what I'm getting with `reducedDim`):

```
##                     PC_1       PC_2       PC_3       PC_4       PC_5
## AAACATACAACCAC  4.792406  0.6655864  0.6816416 -2.5487676 -2.6929942
## AAACATTGAGCTAC -4.345936 15.3062340 11.2202213 -1.7018955 40.0620815
## AAACATTGATCAGC  3.354691  2.0438852  0.8186358 -1.8265953  0.6470771
## AAACCGTGCTTCCG -6.438819 -2.5645224 -3.3215958  3.9079266 -3.7790946
## AAACCGTGTATGCG  5.679727 -3.6266932 -0.1187105 -0.6670379 -2.3010491
## AAACGCACTGGTAC  4.805082 -0.2907679 -0.3126018 -0.8868166 -0.0471751
```

Is this data encoded in the Atlas data somewhere I can find it, and if not is it available somewhere else?

Many thanks for any clarity on this issue!

**Comment by mtekman** [comment]
The specific error message I get when trying to perform the transfer learning is:

`Error: No features to use in finding transfer anchors. To troubleshoot, try explicitly providing features to the features parameter and ensure that they are present in both reference and query assays.`

Some related topics:
* https://github.com/theislab/zellkonverter/issues/62
* https://github.com/satijalab/seurat/issues/5332

**Comment by jonathangriffiths** [comment]
Hi there,

Unfortunately, the objects were made way before featureLoadings were ever a thing, I think. In addition, I am quite some way down the line from the compute servers I used in this project and I will not have access to them again.

Therefore I'm afraid that you'll need to recompute these yourself if you want them! Even so, I'm not quite sure what value they have after MNN correction, since the loadings multiplied by the PC positions will not actually recapitulate the original gene expression values any more.

Sorry I can't provide a nicer solution,
Jonny.

**Comment by mtekman** [comment]
Ah, I see. 

Well, thanks nonetheless. I tried doing my own correction on the timepoint subsets I'm interested in (via MNN, SeuratIntegration, Harmony) but the cell labels just don't match the resulting clusters I do afterwards, and I think that I'd have to re-compute the entire MouseGastrulation data to get the same level of correction....
