### ISSUE TITLE
error in the web server of the mouse gastrulation data

### ISSUE THREAD

**Issue by xwchen0024** [MarioniLab/MouseGastrulationData#23]
<img width="1456" alt="Screenshot 2024-02-17 at 1 21 18 PM" src="https://github.com/MarioniLab/MouseGastrulationData/assets/160347695/03f8cdf7-b39e-4ae1-91a7-34ebf10c77f4">

**Comment by jonathangriffiths** [comment]
Thanks

This is now hard (i.e. impossible) for me to fix, because I don't have access to the server. Please could you get in contact with John Marioni? marioni (at) ebi.ac.uk


If you don't get a reply in a week or so, let me know, and we can try to get in touch with IT at CRUK where it is hosted.

**Comment by xwchen0024** [comment]
Thanks Jon for the information.  I will email Dr. Marioni.
Best,
Xiaowen
________________________________
From: Jonathan Griffiths ***@***.***>
Sent: Saturday, February 17, 2024 1:26 PM
To: MarioniLab/MouseGastrulationData ***@***.***>
Cc: Chen, Xiaowen ***@***.***>; Author ***@***.***>
Subject: [External] Re: [MarioniLab/MouseGastrulationData] error in the web server of the mouse gastrulation data (Issue #23)


Closed #23<https://github.com/MarioniLab/MouseGastrulationData/issues/23> as completed.

**Comment by xwchen0024** [comment]
Hi Jon,
I managed to get access to the website for several days. However, the website is totally unavalable.
Thanks for helping on this. I think your resources are really of high quality and very useful to the community.
Best,
Xiaowen
________________________________
From: Jonathan Griffiths ***@***.***>
Sent: Saturday, February 17, 2024 1:26 PM
To: MarioniLab/MouseGastrulationData ***@***.***>
Cc: Chen, Xiaowen ***@***.***>; Author ***@***.***>
Subject: [External] Re: [MarioniLab/MouseGastrulationData] error in the web server of the mouse gastrulation data (Issue #23)


Thanks

This is now hard (i.e. impossible) for me to fix, because I don't have access to the server. Please could you get in contact with John Marioni? marioni (at) ebi.ac.uk

If you don't get a reply in a week or so, let me know, and we can try to get in touch with IT at CRUK where it is hosted.

**Comment by jonathangriffiths** [comment]
Hi Xiaowen - please can you explain this a little bit for me?

Is the website periodically unstable, or it is completely down at the moment?

Thanks,
Jonny

**Comment by xwchen0024** [comment]
It is completely down now.
Thanks!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jonathan Griffiths ***@***.***>
发送时间: Wednesday, March 6, 2024 12:18:13 PM
收件人: MarioniLab/MouseGastrulationData ***@***.***>
抄送: Chen, Xiaowen ***@***.***>; Author ***@***.***>
主题: [External] Re: [MarioniLab/MouseGastrulationData] error in the web server of the mouse gastrulation data (Issue #23)


Hi Xiaowen - please can you explain this a little bit for me?

Is the website periodically unstable, or it is completely down at the moment?

Thanks,
Jonny

―

**Comment by jonathangriffiths** [comment]
I understand that it is back up now, thanks to work from Andrian Yang & the CRUK CI IT team

**Comment by xwchen0024** [comment]
That is great! Thanks a lot for your help!
Best,
Xiaowen

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jonathan Griffiths ***@***.***>
发送时间: Thursday, March 7, 2024 5:48:56 AM
收件人: MarioniLab/MouseGastrulationData ***@***.***>
抄送: Chen, Xiaowen ***@***.***>; Author ***@***.***>
主题: [External] Re: [MarioniLab/MouseGastrulationData] error in the web server of the mouse gastrulation data (Issue #23)


I understand that it is back up now, thanks to work from Andrian Yang & the CRUK CI IT team

―
