### ISSUE TITLE
Don't dontrun if you can avoid it

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/MouseGastrulationData#5]
`?CelltypePalette`, I'm looking at you.

While I'm looking at that, you know you don't even have to make it a function, right? You can just export the actual vector itself (it can't be modified anyway).

**Comment by jonathangriffiths** [comment]
On the latter point, I had thought about it - but is there a particular reason to prefer it one way or the other? The difference seems marginal.

**Comment by LTLA** [comment]
It just makes it easier for people to figure out what it is - if it doesn't do any work, it shouldn't be a function, because then users might wonder what kind of mystery sauce is happening internally.

You should probably also use `EmbryoCellTypePalette` or something more specific.
