### ISSUE TITLE
Move Atlas UMAP data from colData into reducedDims

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/MouseGastrulationData#6]
Not really sure why it's there... I guess the coordinates were given to you? 

More generally, there should be a more comprehensive description of the various reduced dimension fields in `?(Embryo)AtlasData`, that was previously in the vignette but disappeared.

**Comment by jonathangriffiths** [comment]
https://github.com/MarioniLab/MouseGastrulationData/commit/94b96c29ac95c39eb721e3a84654eaa8aed33c90

I've resolved this in the make-data script. If it is much preferable to fix this on the CI-hosted file, I could do that.
