### ISSUE TITLE
Why are the colours in the data subdirectory?

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/MouseGastrulationData#8]
This is not a good idea.

What, exactly, was wrong with having a variable in the package namespace?

**Comment by jonathangriffiths** [comment]
I don't really understand what the difference is that you're describing, though I have no doubt it would be better as you describe - I had just followed Hadley's data guide.

I'll accept a PR if you submit one

**Comment by LTLA** [comment]
Just do it the way you did it before. Just define a vector in `R/`, document it and you're done. There's plenty of pre-defined variables in base R, e.g., `?cars`. Just have a variable for your colours.

Source code is always preferable to binary objects.

**Comment by jonathangriffiths** [comment]
Done
