### ISSUE TITLE
Puzzles about data

### ISSUE THREAD

**Issue by yandgong307** [MarioniLab/MouseGastrulationData#9]
Hello, I have one question about the data. 

In this paper, mouse embryos between 6.5 to 8.5 were collected and performed scRNA-seq, as I know, a 8.25 whole mouse atlas were obtained in Ximena Ibarra-Soria et al.,2018 Nature cell biology.

So I wondered whether the data in these two papers are same for 8.25 or a new 8.25 data were got.
thanks for your reply.

**Comment by jonathangriffiths** [comment]
Hi there,

It's the same data, but reprocessed (from the read level upwards). So the cells won't be exactly the same.

Jonny
